export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTHENTICATE = "AUTHENTICATE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL";
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL";

export const SHOW_SUCCESS_MODAL = "SHOW_SUCCESS_MODAL";
export const HIDE_SUCCESS_MODAL = "HIDE_SUCCESS_MODAL";

export const FETCH_PUBMED_ARTICLES_BY_QUERY = "FETCH_PUBMED_ARTICLE_BY_QUERY";
export const FETCH_PUBMED_ARTICLE_BY_ID = "FETCH_PUBMED_ARTICLE_BY_ID";
export const CLEAR_PUBMED_ARTICLES = "CLEAR_PUBMED_ARTICLES";

export const FETCH_WIKI_ITEMS_BY_QUERY = "FETCH_WIKI_ITEMS_BY_QUERY";
export const FETCH_WIKI_ITEM_BY_ID = "FETCH_WIKI_ITEM_BY_ID";
export const CLEAR_WIKI_ITEMS = "CLEAR_WIKI_ITEMS";

export const FETCH_MY_ARTICLES = "FETCH_MY_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const FETCH_ARTICLE_BY_ID = "FETCH_ARTICLE_BY_ID";
export const FETCH_PAGINATED_ARTICLES = "FETCH_PAGINATED_ARTICLES";
export const DELETE_ARTICLE_TAG = "DELETE_ARTICLE_TAG";

export const FETCH_USER_DETAILS_BY_ID = "FETCH_USER_DETAILS_BY_ID";